# Generated by Django 3.2.5 on 2021-07-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('present_dey1', models.BooleanField(default=False)),
                ('present_dey2', models.BooleanField(default=False)),
                ('present_dey3', models.BooleanField(default=False)),
                ('present_dey4', models.BooleanField(default=False)),
                ('present_dey5', models.BooleanField(default=False)),
                ('present_dey6', models.BooleanField(default=False)),
                ('present_dey7', models.BooleanField(default=False)),
                ('present_dey8', models.BooleanField(default=False)),
                ('present_dey9', models.BooleanField(default=False)),
                ('present_dey10', models.BooleanField(default=False)),
                ('present_dey11', models.BooleanField(default=False)),
                ('present_dey12', models.BooleanField(default=False)),
                ('present_dey13', models.BooleanField(default=False)),
                ('present_dey14', models.BooleanField(default=False)),
                ('present_dey15', models.BooleanField(default=False)),
                ('present_dey16', models.BooleanField(default=False)),
                ('present_dey17', models.BooleanField(default=False)),
                ('present_dey18', models.BooleanField(default=False)),
                ('present_dey19', models.BooleanField(default=False)),
                ('present_dey20', models.BooleanField(default=False)),
                ('present_dey21', models.BooleanField(default=False)),
                ('present_dey22', models.BooleanField(default=False)),
                ('present_dey23', models.BooleanField(default=False)),
                ('present_dey24', models.BooleanField(default=False)),
                ('present_dey25', models.BooleanField(default=False)),
                ('present_dey26', models.BooleanField(default=False)),
                ('present_dey27', models.BooleanField(default=False)),
                ('present_dey28', models.BooleanField(default=False)),
                ('present_dey29', models.BooleanField(default=False)),
                ('present_dey30', models.BooleanField(default=False)),
                ('present_dey31', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students', unique_for_month='date', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Місячний Журнал',
                'verbose_name_plural': 'Місячні Журнали',
            },
        ),
    ]
