# Generated by Django 3.2.5 on 2021-07-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210709_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday date'),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Second Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='students',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional notes'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.groups', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='students',
            name='ticket',
            field=models.CharField(max_length=256, verbose_name='Ticket'),
        ),
    ]
